apiVersion: skaffold/v1alpha3
kind: Config
build:
  artifacts:
    - imageName: manifesthub/mqtt-svc-ex
      docker:
        dockerfilePath: docker/Dockerfile
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  local:
    skipPush: false
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - k8s/mqtt-svc-ex.yaml
    - k8s/mqtt-svc-ex-config.yaml
    - k8s/mqtt-svc-ex-environment.yaml
    - k8s/mqtt-svc-ex-headless.yaml
